### PR TITLE
Minor typos in Lab.md

### PR DESCRIPTION
**Pull request by panjkov**
Adressing #5 and #6. I cannot upload photos with fixed typo, but at least I'm fixing typos in text and code, as discussed on TTT call.

@VesaJuvonen @andrewconnell

### CODE REVIEW

**Comment by andrewconnell** [comment]
Thanks... we'll get these incorporated next time we do a pass on the module. Updating the lab is one part... the completed solutions also need to get updated at the same time.

**Comment by panjkov** [comment]
I can step up with those, I also have solutions updated. If that is OK for you?

Dragan Panjkov • panjkov@hotmail.com • www.dragan-panjkov.com

________________________________

**Comment by andrewconnell** [comment]
Fine by me... please don't upload new solutions... just edits where necessary. Then again, I'll be doing it when I do the pass... so up to you (and appreciated!). :)

**Comment by andrewconnell** [comment]
The issues submitted in this PR were fixed in a previous refresh, so closing this PR. Thanks for your contribution!

**Pull request closed without merging**
